language: node_js
node_js:
  - "stable"

deploy:
  provider: pages
  edge: true            # use dpl v2
  strategy: git
  token: $GITHUB_TOKEN  # <-- uses the env var you set
  local_dir: build
  keep_history: false
  on:
    branch: main
